jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: "./public/"
    steps:
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v4
